version: '3.7'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'tray'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: "101010"
    volumes:
      - ./db:/var/lib/mysql
  api:
    build:
      context: "./api"
      dockerfile: Dockerfile
    image: 'api'
    ports:
      - 8080:80
    volumes:
      - ./api:/var/www/html
  app:
    build:
      context: "./app"
      dockerfile: Dockerfile
    image: 'app'
    ports:
      - 8081:80
    volumes:
      - ./app:/var/www/html