version: '3.7'
services:
  tray-db:
    image: mysql:5.7
    container_name: tray-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'tray'
      MYSQL_ROOT_PASSWORD: "101010"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
  tray-nginx:
    image: nginx
    container_name: tray-nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
      - ./app:/var/www/html/app
      - ./api:/var/www/html/api
    ports:
      - 80:80
    restart: always
    depends_on:
      - tray-fpm
  tray-fpm:
    build: ./docker/fpm
    container_name: tray-fpm
    restart: always
    volumes:
      - ./docker/fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./app:/var/www/html/app
      - ./api:/var/www/html/api